* Coq-config

  Simple script to set up a Coq project dependencies using /opam/.
  Inspired by Haskell's ~stack~.

** Documentation
   Reads ~coq_config.yaml~ file and set up am /opam/ /switch/ and install
   required packages.

   Optionally checks out some sub-projects from /git/ (an alternative
   to using sub-modules).

   It is safe to run multiple times. The /opam/ packages where the
   version numer was specified, will be pinned, so it is safe to do
   `opam update` aftewards.

** TODO
   - [ ] Run ~opam init~ is necessary
   - [ ] If switch exists, check if the right compiler is used and
     update if necessary.
   - [ ] When adding repositories, check their URLs, not just names.
     It they do not match the config - report errror.
   - [ ] Run ~coq-config~ for all ~extra-deps~
   - [ ] pass-through "-j" command line option
   - [ ] When re-running, make sure pinned version removed or updated
     if changed.

** Installation
*** Python packages (install with ~pip~):   
   - click
   - pyyaml
   - cerberus
*** ~opam~ 
    Tested with verson 2.0.5.
